Resistor = 10

[User]
  BetaId = ""
  Name = ""

[Battery]
  BetaRef = ""
  Type = ""
  Voltage = 0
  Brand = ""
  Model = ""

[Regenbox]
  Mode = "Charger"
  NbHalfCycles = 10
  UpDuration = "24h0m0s"
  DownDuration = "24h0m0s"
  TopVoltage = 1500
  BottomVoltage = 900
  Ticker = "10s"
  ChargeFirst = false

[Web]
  ListenAddr = "localhost:3636"
  StaticDir = "static"
  DataDir = "data"
  WebsocketInterval = "1s"

[Watcher]
  ConnPollRate = "1s"

[Serial]
  BaudRate = 57600
  DataBits = 8
  Parity = 0
  StopBits = 0
